### ISSUE TITLE
Wide outputs from WebGrade results in unreadable formatting

### ISSUE THREAD

**Issue by hbiede** [cbourke/grade#13]
See attached image
<img width="1920" alt="Screen Shot 2020-01-25 at 7 58 25 PM" src="https://user-images.githubusercontent.com/6586509/73129594-481d6700-3fad-11ea-801b-69056b55d64d.png">

**Comment by cbourke** [comment]
Should be addressed (partially) with a380086 

Mostly fixed with the pre tag style sheet updates, but I took the opportunity to upgrade jquery, bootstrap and google code prettifier for the student-facing front end.  I'll leave this issue open for a while to see if there are regressions.  I'll make similar updates to the grader-facing end if this is an improvement.
